const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(process.argv[2],'utf8');
const flush=source.slice(source.indexOf('    const flushStream = useCallback'),source.indexOf('    useEffect(() => () => clearTimeout(streamTimer.current)'));
const ctx={useCallback:f=>f,streamTimer:{current:null},streamBuffer:{current:{text:'first token',reasoning:''}},liveReplyId:{current:null},clearTimeout(){},nowId:()=> 'live',setStreamingId:id=>ctx.id=id,setMessages:f=>ctx.messages=f(ctx.messages),messages:[]};
vm.createContext(ctx);vm.runInContext(flush+'\nthis.flush=flushStream;',ctx);ctx.flush();assert.equal(ctx.messages[0].content,'first token');assert.equal(ctx.id,'live');ctx.streamBuffer.current={text:' more',reasoning:'thought'};ctx.flush();assert.equal(ctx.messages.length,1);assert.equal(ctx.messages[0].content,'first token more');assert.equal(ctx.messages[0].reasoning,'thought');console.log('Stream chunks render without message.start and append without duplicates');
const recovery=source.slice(source.indexOf('    // A completion event can be lost'),source.indexOf('    // ── keyboard shortcuts'));
Object.assign(ctx,{useEffect:f=>ctx.cleanup=f(),generating:true,selected:{id:'chat'},historyRequest:{current:2},promptAccepted:{current:true},lastReplyEvent:{current:0},gwSidRef:{current:'live'},gwRef:{current:{status:'open',request:async()=>({output:'Session ID: stored\nAgent Running: No'})}},str:String,BASE:'/chat',PAGE:80,setInterval:f=>{ctx.check=f;return 1},clearInterval(){},fetchJSON:async()=>({messages:[{id:'stored-answer',role:'assistant',content:'Recovered answer',timestamp:123}]}),discardStream(){},setSelected:f=>ctx.selected=f(ctx.selected),setGenerating:v=>ctx.generating=v,refreshSessions(){},setStreamingId:id=>ctx.id=id});
vm.runInContext(recovery,ctx);
(async()=>{await ctx.check();assert.equal(ctx.messages.at(-1).content,'Recovered answer');assert.equal(ctx.generating,false);assert.equal(ctx.selected.key,'stored');const count=ctx.messages.length;ctx.cleanup();await ctx.check();assert.equal(ctx.messages.length,count);console.log('Missed completion recovers the stored reply without resending a prompt');})();
